# Enable validating this file
version: ~> 1.0

language: python
python:
    - "3.6"

sudo: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsdl2-dev

jobs:
  include:
    - script: ./build.sh
      name: "build"
